project: 'ppo-mujoco'
program: train.py
method: grid
name: "HalfCheetah-VPG"

parameters:
  algorithm:
    value: vpg
  num-envs:
    value: 16
  total-steps:
    value: 1000000
  rollout-steps:
    value: 16
  gamma:
    value: 0.99
  save-interval:
    value: 100000
  env-name:
    value: HalfCheetah-v5
  save-path:
    value: 'weights/halfcheetah/vpg/model.pt'
  policy-lr:
    value: 0.0003
  value-lr: 
    value: 0.001
  seed:
    values: [1, 2, 3]

  gae-lambda:
    value: 0.95
  value-epochs:
    value: 10

  optim:
    value: adam
  optim-epsilon:
    value: 0.00001