project: 'ppo-mujoco'
program: train.py
method: grid
name: "Walker2d-A2C"

parameters:
  algorithm:
    value: a2c
  num-envs:
    value: 16
  total-steps:
    value: 1000000
  rollout-steps:
    value: 16
  gamma:
    value: 0.99
  save-interval:
    value: 100000
  env-name:
    value: Walker2d-v5
  save-path:
    value: 'weights/walker2d/a2c/model.pt'
  policy-lr:
    value: 0.0007
  value-lr: 
    value: 0.0007
  seed:
    values: [1, 2, 3]

  gae-lambda:
    value: 0.95
  ent-coef:
    value: 0.001

  optim:
    value: rmsprop
  optim-epsilon:
    value:  0.00001
  optim-alpha:
    value: 0.99